### ISSUE TITLE
Cannot find module 'eco'

### ISSUE THREAD

**Issue by cameronjroe** [docpad/docpad-plugin-eco#7]
Installed `"docpad-plugin-eco": "~2.1.0"`, and running `"docpad": "~6.78.1"`.

DocPad isn't finding the module: `Cannot find module 'eco'`

I also have consolidate installed which seems to be looking for the module as well.

**Comment by RobLoach** [comment]
Does it still break if you use:

```
npm install eco --save
```
?

**Comment by cameronjroe** [comment]
Yeah, 
```
Error: Rendering the extension "eco" to "html" on "site/src/render/index.html.eco" didn't do anything.
Explanation here: http://docpad.org/extension-not-rendering
```

**Comment by RobLoach** [comment]
@cameronjroe You might enjoy having a look at http://github.com/robloach/docpad-plugin-consolidate too. Might glue the peices together nicely for ya. Might also need an update.

**Comment by cameronjroe** [comment]
I did have a look. I'm just wondering why there's a separate plugin for eco if it can be used from consolidate..?

**Comment by RobLoach** [comment]
> I did have a look. I'm just wondering why there's a separate plugin for eco if it can be used from consolidate..?

Eco was created before Consolidate was in place. Would appreciate some PRs on things to keep them up to date too!
